### PR TITLE
Group vite packages together

### PR DESCRIPTION
**Pull request by Zinggi**
The ruby package and the vite js + plugin packages should be upgraded together

### CODE REVIEW

**Comment by Zinggi** [comment]
I haven't tested this, but I think it should work. Is there a way to test these changes?

**Comment by andyundso** [comment]
I usually test it on regex101.com. otherwise, you can apply the rule in a single-project first before upstreaming.

**Comment by Zinggi** [comment]
The regex is correct.
@andyundso Do you think I should really test in on real project first? I would have just merged it, as it takes quite some time to test it.

**Review by andyundso — APPROVED** [review]
Go ahead :)

**Pull request merged**
